project: htfl-ondevice

code:
  # Path to the code root dir, relative to the config file
  # Defaults to the config file dir if omitted
  # The working directory is set to this path
  path: "../"
  client:
    command: >-
      ./config_device_data.sh ${COLEXT_DATASETS}/iWildCam ${COLEXT_CLIENT_ID} &&
      python3 -m system.clients.clientFD
      --server_address=${COLEXT_SERVER_ADDRESS}
      --num_classes=158
  server:
    command: >-
      python3 -m system.servers.serverFD
      --min_fit_clients=${COLEXT_N_CLIENTS}
      --min_available_clients=${COLEXT_N_CLIENTS}
      --num_rounds=10

clients:
  - dev_type: JetsonAGXOrin
    count: 1
    # Add additional arguments to this client group
    add_args: "--model=ResNet101"

  - dev_type: JetsonOrinNano
    count: 2
    add_args: "--model=ResNet50"

  - dev_type: OrangePi5B
    count: 2
    add_args: "--model=ResNet18"

  - dev_type: OrangePi5B
    # If `count` is not specified, it's assumed to be 1
    add_args: "--model=ResNet34"
